spring:
  application:
    name: identity-service

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            issuer-uri: https://accounts.google.com

server:
  port: 8081

identity-service:
  host: http://localhost:8081
  public-base-url: /v1/api/users
  auth-base-url: /v1/api/users/auth
  self-base-url: /v1/api/users/self
  jwt:
    user-secret-key: ${JWT_USER_SECRET_KEY}
