services:

  #Microservices
  identity-service:
    container_name: identity-service
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    ports:
      - "${IDENTITY_PORT}:8081"
    depends_on:
      - identity_service_postgres
      - kafka
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://identity_service_postgres:5432/${IDENTITY_DB}
      SPRING_DATASOURCE_USERNAME: "${IDENTITY_USER}"
      SPRING_DATASOURCE_PASSWORD: "${IDENTITY_PASS}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ${NETWORK_NAME}

  course-service:
    container_name: course-service
    build:
      context: ./course-service
      dockerfile: Dockerfile
    ports:
      - "${COURSE_PORT}:8082"
    depends_on:
      - course_service_postgres
      - kafka
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://course_service_postgres:5432/${COURSE_DB}
      SPRING_DATASOURCE_USERNAME: "${COURSE_USER}"
      SPRING_DATASOURCE_PASSWORD: "${COURSE_PASS}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ${NETWORK_NAME}

  media-stock-service:
    container_name: media-stock-service
    build:
      context: ./media-stock-service
      dockerfile: Dockerfile
    ports:
      - "${MEDIA_STOCK_PORT}:8083"
    depends_on:
      - kafka
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    networks:
      - ${NETWORK_NAME}

  rating-service:
    container_name: rating-service
    build:
      context: ./rating-service
      dockerfile: Dockerfile
    ports:
      - "${RATING_PORT}:8084"
    depends_on:
      - rating_service_postgres
      - kafka
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://rating_service_postgres:5432/${RATING_DB}
      SPRING_DATASOURCE_USERNAME: "${RATING_USER}"
      SPRING_DATASOURCE_PASSWORD: "${RATING_PASS}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    networks:
      - ${NETWORK_NAME}

  #Databases-Postgres
  identity_service_postgres:
    container_name: identity_service_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "${IDENTITY_DB}"
      POSTGRES_USER: "${IDENTITY_USER}"
      POSTGRES_PASSWORD: "${IDENTITY_PASS}"
    ports:
      - "${IDENTITY_DB_PORT}:5432"
    restart: always
    volumes:
      - identity_postgres_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}

  course_service_postgres:
    container_name: course_service_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "${COURSE_DB}"
      POSTGRES_USER: "${COURSE_USER}"
      POSTGRES_PASSWORD: "${COURSE_PASS}"
    ports:
      - "${COURSE_DB_PORT}:5432"
    restart: always
    volumes:
      - course_postgres_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}

  rating_service_postgres:
    container_name: rating_service_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "${RATING_DB}"
      POSTGRES_USER: "${RATING_USER}"
      POSTGRES_PASSWORD: "${RATING_PASS}"
    ports:
      - "${RATING_DB_PORT}:5432"
    restart: always
    volumes:
      - rating_postgres_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}

  #Eureka Service Registry
  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "${EUREKA_PORT}:8761"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ${NETWORK_NAME}

  #Redis
  redis:
    container_name: coursehub-redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    networks:
      - ${NETWORK_NAME}

  #Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: coursehub-zookeeper
    restart: always
    networks:
      - ${NETWORK_NAME}
    environment:
      ZOOKEEPER_CLIENT_PORT: "${ZOOKEEPER_CLIENT_PORT}"
      ZOOKEEPER_TICK_TIME: "${ZOOKEEPER_TICK_TIME}"

  #Kafka
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: coursehub-kafka
    networks:
      - ${NETWORK_NAME}
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    restart: always
    environment:
      KAFKA_BROKER_ID: "${KAFKA_BROKER_ID}"
      KAFKA_ZOOKEEPER_CONNECT: "${KAFKA_ZOOKEEPER_CONNECT}"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}"
      KAFKA_LISTENERS: "${KAFKA_LISTENERS}"
      KAFKA_ADVERTISED_LISTENERS: "${KAFKA_ADVERTISED_LISTENERS}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}"
      KAFKA_INTER_BROKER_LISTENER_NAME: "${KAFKA_INTER_BROKER_LISTENER_NAME}"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: coursehub-kafka-ui
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - kafka
    ports:
      - "${KAFKA_UI_PORT}:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=coursehub_cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

networks:
  ${NETWORK_NAME}:
    driver: bridge

volumes:
  identity_postgres_data:
  course_postgres_data:
  rating_postgres_data:
