spring:
  application:
    name: rating-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5435/ch_rts_db
    username: ch_rts_user
    password: dbhunter
    driver-class-name: org.postgresql.Driver

server:
  port: 8084

services:
  identity:
    secret-key: Z+2hXkMTIW+S3IlblVk48SRQgy31QhFu25BP84SNlSU=

